export const { TARGET_S3_BUCKET, USER_POOL_ID, USER_POOL_CLIENT_ID, AUTH_FLOW } = process.env;

export const REFRESH_TOKEN_AUTH_FLOW = 'REFRESH_TOKEN_AUTH';

export const SMS_MFA = 'SMS_MFA';

export const SOFTWARE_TOKEN_MFA = 'SOFTWARE_TOKEN_MFA';

export const SELECT_MFA_TYPE = 'SELECT_MFA_TYPE';

export const MFA_SETUP = 'MFA_SETUP';

export const PASSWORD_VERIFIER = 'PASSWORD_VERIFIER';

export const CUSTOM_CHALLENGE = 'CUSTOM_CHALLENGE';

export const DEVICE_SRP_AUTH = 'DEVICE_SRP_AUTH';

export const DEVICE_PASSWORD_VERIFIER = 'DEVICE_PASSWORD_VERIFIER';

export const ADMIN_NO_SRP_AUTH = 'ADMIN_NO_SRP_AUTH';

export const NEW_PASSWORD_REQUIRED = 'NEW_PASSWORD_REQUIRED';
