Description: project resources
Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_TABLE}
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.TARGET_S3_BUCKET}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT]
            AllowedOrigins: ['*']
            Id: CORSRuleId1
            MaxAge: '3600'

  UserTableStreamParameter:
    DeletionPolicy: Retain
    Type: AWS::SSM::Parameter
    DependsOn: ProductsTable
    Properties:
      Description: PRODUCTS_TABLE_STREAM_ARN
      Name: ${self:service}-products-stream-${opt:stage, self:provider.stage, "dev"}
      Type: String
      Value: !GetAtt ProductsTable.StreamArn
      # Value: ${fetchStreamARN(${self:provider.environment.DYNAMODB_TABLE})}
      # Value: ${fetchStreamARN(${self:custom.TableName})}
# params:
#   TableName: !GetAtt ProductsTable.TableName
